application: your-app-id
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /
  static_files: templates/index.html
  upload: templates/index\.html

- url: /cursor/.*
  script: suggest_cursor.APPLICATION

- url: /unique/.*
  script: suggest_unique.APPLICATION

libraries:
- name: jinja2
  version: "2.6"
