application: paging-example
version: 1
runtime: python
api_version: 1

handlers:

- url: /
  static_files: index.html
  upload: index.html

- url: /key/.*
  script: suggest_key.py

- url: /unique/.*
  script: suggest_unique.py
